version: "3"

services:
  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    # depends_on:
    #   - db
    tty: true
    stdin_open: true
    

  # frontend:
  #   build: ./frontend
  #   container_name: frontend_container
  #   depends_on:
  #     - backend
  #   ports:
  #     - 8000:8000
  #   environment:
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     - ./frontend:/app:rw
  #   tty: true
  #   stdin_open: true

  # db:
  #   image: mysql:5.7
  #   platform: linux/amd64
  #   container_name: db_container
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   env_file:
  #     - .env

volumes:
  mysql: